import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  useEffect(() => {
    (async () => {
      const response = await fetch(process.env.NEXT_PUBLIC_LOGINSALESFORD);
      const token = await response.json();

      localStorage.setItem("token", token);
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>FAKETWITAH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </div>
  );
}
